# Generated by Django 5.1.7 on 2025-03-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_tbl',
            old_name='mod',
            new_name='mob',
        ),
    ]
