# Generated by Django 5.1.7 on 2025-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_mod_reg_tbl_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='pet_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnm', models.CharField(max_length=25)),
                ('pim', models.FileField(upload_to='pic')),
                ('prc', models.IntegerField()),
                ('des', models.TextField()),
            ],
        ),
    ]
