# Generated by Django 5.1.7 on 2025-04-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_pet_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.reg_tbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.pet_tbl')),
            ],
        ),
    ]
